<?php

$preload = true;

if ($preload === false) {
    return '';
}
?>
<script>
    require([
        'domReady',
        'jquery',
        'mage/apply/main',
        'mage/apply/scripts',
        'underscore',
    ], function (domReady, $, mage) {
        domReady(function () {
            mage.apply();

            $('body').on('contentUpdated', function () {
                mage.apply();
            });
        });
    });
</script>
